spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/ferry
  session:
    store-type: none
security:
  basic:
    enabled: false
